### ISSUE TITLE
On Comment Deletion Replies Also Deleted 

### ISSUE THREAD

**Issue by Noor-infoarc** [RiyaNegi/react-comments-section#12]
Hi there,

I wanted to ask if there is any way that the code could be adjusted to only delete the selected comment and not all the linked comments (replies) with it. If so, please guide me on how to do it.

Thank you.

**Comment by RiyaNegi** [comment]
@Noor-infoarc Hey so when you delete the parent comment, naturally all it's children comment's will get deleted as well. The children comment won't make any sense without it's parent comment as they are dependent on them. But if you delete the child comment or individual/single comments that are independent, only the selected one's will get deleted.

**Comment by Noor-infoarc** [comment]
I understand. It does make sense especially since you are using the YouTube and Instagram model.

Thank you for the reply.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
