### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by PublicTrades** [RiyaNegi/react-comments-section#17]
Trying to install package but getting this error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-comments-section@2.0.10
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0 || ^18.0.0" from @apollo/client@3.7.9
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.6.9" from the root project
npm ERR!   42 more (@bedrock-layout/use-forwarded-ref, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-comments-section@2.0.10
npm ERR! node_modules/react-comments-section
npm ERR!   react-comments-section@"^2.0.10" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.0.0" from react-comments-section@2.0.10
npm ERR!   node_modules/react-comments-section
npm ERR!     react-comments-section@"^2.0.10" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/admin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2023-03-22T16_39_09_958Z-debug-0.log

```
Any idea how to resolve?

**Comment by fgervasoni** [comment]
You can workaround this error with
`npm i react-comments-section --force`

after that you have to install the uuid module with
`npm install uuid --force`

and than insert this script in your index.html
`<script>
    const global = globalThis;
</script>`

**Comment by Jarid-Resi** [comment]
> You can workaround this error with `npm i react-comments-section --force`
> 
> after that you have to install the uuid module with `npm install uuid --force`
> 
> and than insert this script in your index.html `<script> const global = globalThis; </script>`

Great package for getting started with supporting comments for React apps!

I think it would be extremely helpful for outlining the need of this script in the index.html in the docs. I do not see this mentioned in the getting started section of the documentation. 

In my opinion it be more appreciated to not need this however if that is not an easy fix explaining the need for it is a good start
