### ISSUE TITLE
I'm getting errors when installing this library??

### ISSUE THREAD

**Issue by CantCode023** [RiyaNegi/react-comments-section#4]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-authentication@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-comments-section@1.0.7
npm ERR! node_modules/react-comments-section
npm ERR!   react-comments-section@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\User\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2022-03-20T03_35_57_976Z-debug.log

**Comment by B-Simms** [comment]
Same here.

**Comment by RiyaNegi** [comment]
Fixed, install the new version.

**Comment by JackScofield** [comment]
Still get the same err. I am on React 18.2.0.

**Comment by asrinutku** [comment]
Still get the same err. I am on React 18.2.0.
